---
-
  name: Deploy Application
  hosts: all
  gather_facts: false
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_deploy_to: /var/www/html/symfony-app
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: "rsync"
    ansistrano_shared_paths:
      - var/log
      - var/sessions
    symfony_console_path: 'bin/console'
    symfony_run_assetic_dump: false
    symfony_run_doctrine_migrations: true
  roles:
      - { role: cbrunnkvist.ansistrano-symfony-deploy }
  environment:
    APP_ENV: "{{ sf_env }}"
    BASE_URL: "{{ sf_base_url }}"
    HOST: "{{ sf_host }}"
    SCHEME: "{{ sf_scheme }}"
